name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      - run: cargo test --verbose
  check:
    name: Fmt/lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      - run: cargo fmt -- --check
      - run: cargo check --verbose
